apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ Values.appName }}
  labels:
    app: {{ Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ Values.appName }}
  template:
    metadata:
      labels:
        app: {{ Values.appName }}
    spec:
      imagePullSecrets:
      - name: gitlab-registry-key
      containers:
      - name: {{ Values.appName }}
        image: "{{ Values.image.name }}:{{ Values.image.version }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80