apiVersion: v1
kind: Service
metadata:
  name: {{ Values.appName }}
  labels:
    app: {{ Values.appName }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: {{ Values.appName }}