apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: MY-YAML-MANIFEST-REPOSITORY-URL
    targetRevision: HEAD
    path: Code
  destination: 
    server: https://kubernetes.default.svc
    namespace: netflix

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true