apiVersion: v1
kind: Secret
metadata:
 name: argocd-repo
 namespace: argocd
 labels:
  argocd.argoproj.io/secret-type: repository
stringData:
 type: git
 url: MY-YAML-MANIFEST-REPOSITORY-URL
 username: Argocd
 password: MY-YAML-MANIFEST-REPOSITORY-PASSWORD(ACCESS-TOKEN)