---
- name: Downloading the tools, Docker and Minikube
  hosts: all
  become: yes
  become_method: sudo

  tasks:
  - name: Installing tools
    apt:
     name:
     - apt-transport-https
     - ca-certificates
     - curl
     - gnupg-agent
     - software-properties-common
     - snap
     
  - name: Adding Docker apt-key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg

  - name: Adding Docker Repository
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu focal stable
  
  - name: Installing Docker
    apt:
     name:
     - docker-ce
     - docker-ce-cli
     - containerd.io
     update_cache: yes

  - name: Giving UserPermission 
    shell: usermod -aG docker vagrant
    shell: sudo usermod -aG docker $USER && newgrp docker

  - name: Downloading Minikube
    get_url:
     url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
     dest: /home/vagrant/minikube_latest_amd64.deb
     mode: '0644'
  
  - name: Installing Minikube
    apt:
     deb: /home/vagrant/minikube_latest_amd64.deb

  - name: Install KubeCtl
    community.general.snap:
     name: kubectl
     classic: yes

- name: Starting the Minikube cluster and checking status
  hosts: all

  tasks:    
  - name: starting minikube
    shell: minikube start --vm-driver=docker 

  - name: Checking status of the cluster
    shell: minikube status
    shell: kubectl get pods

    
  